In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Akshat Sharma\OneDrive\Desktop\Data Science\Machine learning\Decision Tree\Imarticus Dataset\Decision Tree Project\Dataset 2\Random Forest Project\Dataset\TaxiFare.csv", parse_dates= ["date_time_of_pickup"])

In [3]:
df = df.loc[5686:5814]
df

,unique_id,amount,date_time_of_pickup,longitude_of_pickup,latitude_of_pickup,longitude_of_dropoff,latitude_of_dropoff,no_of_passenger
5686,15:00.0,3.3,2011-07-30 11:15:00+00:00,-73.947235,401.083332,-73.951392,40.778927,1
5687,58:00.0,4.5,2012-02-05 19:58:00+00:00,-73.984175,40.764895,-73.982092,40.774732,2
5688,50:40.0,4.9,2011-09-07 21:50:40+00:00,-73.986700,40.761300,-73.982300,40.773900,0
5689,52:00.0,9.3,2010-10-22 10:52:00+00:00,-73.975335,40.749957,-73.982862,40.769070,1
5690,19:16.0,12.9,2011-01-09 16:19:16+00:00,-73.989635,40.741479,-73.962491,40.710028,1
...,...,...,...,...,...,...,...,...
5810,41:07.0,7.5,2015-01-08 06:41:07+00:00,-73.950760,40.771313,-73.954155,40.787369,1
5811,49:00.0,12.1,2012-02-17 14:49:00+00:00,-73.982392,40.745740,-73.990915,40.750645,6
5812,23:00.0,4.1,2012-06-29 00:23:00+00:00,-73.992150,40.725847,-73.984287,40.725557,2
5813,01:00.0,5.0,2014-04-25 00:01:00+00:00,-73.974463,40.742537,-73.983933,40.743862,2
5814,09:03.0,10.0,2014-10-22 17:09:03+00:00,-73.959037,40.777711,-73.982267,40.778881,1

In [4]:
import numpy as np
import pandas as pd
import requests  # Import the 'requests' module

# Replace 'YOUR_API_KEY' with your actual MapQuest API key
api_key = 'X7cJj9zoikK2PZ6dh2js1FI2iNerlk29'

# Initialize an empty list to store distances
distances = []

# Iterate through the DataFrame rows and calculate distances
for index, row in df.iterrows():
    pickup = f"{row['latitude_of_pickup']},{row['longitude_of_pickup']}"
    dropoff = f"{row['latitude_of_dropoff']},{row['longitude_of_dropoff']}"
    
    url = f"https://www.mapquestapi.com/directions/v2/route?key={api_key}&from={pickup}&to={dropoff}&routeType=fastest"
    
    try:
        response = requests.get(url)
        response_data = response.json()

        if "route" in response_data and len(response_data["route"]["legs"]) > 0:
            distance = response_data["route"]["distance"]
            distances.append(distance)
            print(f"Distance for index {index}: {distance} miles")
        else:
            print(f"No route data for index {index}")
    except:
        distances.append(np.nan)

No route data for index 5686
Distance for index 5687: 0.7655 miles
Distance for index 5688: 0.9892 miles
Distance for index 5689: 2.0195 miles
Distance for index 5690: 3.7481 miles
Distance for index 5691: 1.5497 miles
Distance for index 5692: 0.8637 miles
Distance for index 5693: 2.0673 miles
Distance for index 5694: 2.0437 miles
Distance for index 5695: 2.2692 miles
Distance for index 5696: 0.5878 miles
Distance for index 5697: 1.4907 miles
Distance for index 5698: 8.4836 miles
Distance for index 5699: 4.2694 miles
Distance for index 5700: 0.5257 miles
Distance for index 5701: 1.2278 miles
Distance for index 5702: 0.9147 miles
Distance for index 5703: 1.0364 miles
Distance for index 5704: 0.9861 miles
Distance for index 5705: 0.6879 miles
Distance for index 5706: 1.8697 miles
Distance for index 5707: 4.0016 miles
Distance for index 5708: 1.2695 miles
Distance for index 5709: 12.6573 miles
Distance for index 5710: 3.338 miles
Distance for index 5711: 3.9103 miles
Distance for index 5712: 18.9754 miles
Distance for index 5713: 2.7347 miles
Distance for index 5714: 9.9426 miles
Distance for index 5715: 12.3448 miles
Distance for index 5716: 0.6798 miles
Distance for index 5717: 8.9241 miles
Distance for index 5718: 1.2595 miles
Distance for index 5719: 0 miles
Distance for index 5720: 1.5037 miles
Distance for index 5721: 1.5292 miles
Distance for index 5722: 2.0499 miles
Distance for index 5723: 5.8111 miles
Distance for index 5724: 1.6212 miles
Distance for index 5725: 2.4277 miles
Distance for index 5726: 3.0261 miles
Distance for index 5727: 1.2539 miles
Distance for index 5728: 1.8709 miles
Distance for index 5729: 2.1605 miles
Distance for index 5730: 0.7637 miles
Distance for index 5731: 1.0582 miles
Distance for index 5732: 9.7145 miles
Distance for index 5733: 1.3658 miles
Distance for index 5734: 4.8542 miles
Distance for index 5735: 9.7754 miles
Distance for index 5736: 1.6914 miles
Distance for index 5737: 0.4493 miles
Distance for index 5738: 15.0664 miles
Distance for index 5739: 0.7376 miles
Distance for index 5740: 2.693 miles
Distance for index 5741: 1.4689 miles
Distance for index 5742: 2.7247 miles
Distance for index 5743: 0.5002 miles
Distance for index 5744: 1.1172 miles
Distance for index 5745: 2.1636 miles
Distance for index 5746: 1.0041 miles
Distance for index 5747: 2.6669 miles
Distance for index 5748: 2.785 miles
Distance for index 5749: 1.2347 miles
Distance for index 5750: 2.4731 miles
Distance for index 5751: 1.0271 miles
Distance for index 5752: 0.233 miles
Distance for index 5753: 0.9973 miles
Distance for index 5754: 3.9451 miles
Distance for index 5755: 1.5795 miles
Distance for index 5756: 1.0035 miles
Distance for index 5757: 2.7098 miles
Distance for index 5758: 2.5743 miles
Distance for index 5759: 2.1773 miles
Distance for index 5760: 3.4318 miles
Distance for index 5761: 1.3316 miles
Distance for index 5762: 1.7355 miles
Distance for index 5763: 2.0263 miles
Distance for index 5764: 6.0851 miles
Distance for index 5765: 0 miles
Distance for index 5766: 0.3517 miles
Distance for index 5767: 0.5866 miles
Distance for index 5768: 1.5379 miles
Distance for index 5769: 0.8128 miles
Distance for index 5770: 2.7868 miles
Distance for index 5772: 0.9153 miles
Distance for index 5773: 8.9279 miles
Distance for index 5774: 1.3453 miles
Distance for index 5775: 3.2231 miles
Distance for index 5776: 3.0571 miles
Distance for index 5777: 1.2409 miles
Distance for index 5778: 6.9208 miles
Distance for index 5780: 1.4646 miles
Distance for index 5781: 2.6421 miles
Distance for index 5782: 1.8101 miles
Distance for index 5783: 0.7115 miles
Distance for index 5784: 0.7233 miles
Distance for index 5785: 1.9865 miles
Distance for index 5786: 0.5978 miles
Distance for index 5787: 2.1288 miles
Distance for index 5788: 0.791 miles
Distance for index 5789: 3.5039 miles
Distance for index 5790: 1.8175 miles
Distance for index 5791: 1.0346 miles
Distance for index 5792: 1.8306 miles
Distance for index 5793: 0.924 miles
Distance for index 5794: 1.1321 miles
Distance for index 5795: 14.4407 miles
Distance for index 5797: 2.3047 miles
Distance for index 5798: 1.7703 miles
Distance for index 5799: 0.5822 miles
Distance for index 5800: 1.2483 miles
Distance for index 5801: 1.1881 miles
Distance for index 5802: 0.6661 miles
Distance for index 5803: 0.3952 miles
Distance for index 5804: 6.7009 miles
Distance for index 5805: 0.5375 miles
Distance for index 5806: 1.0619 miles
Distance for index 5807: 17.6575 miles
Distance for index 5808: 2.3103 miles
Distance for index 5809: 1.7063 miles
Distance for index 5810: 1.5907 miles
Distance for index 5811: 0.878 miles
Distance for index 5812: 0.5717 miles
Distance for index 5813: 0.7326 miles
Distance for index 5814: 1.8324 miles

In [5]:
len(distances)

128

In [8]:
df_1 = df.drop(index = 5686)

In [9]:
df_1["distance_in_miles"] = distances

In [10]:
df_1.to_csv(r"C:\Users\Akshat Sharma\OneDrive\Desktop\Data Science\Machine learning\Decision Tree\Imarticus Dataset\Decision Tree Project\Dataset 2\Random Forest Project\Dataset\df2.csv", index=False)